

replicaCount: 1

image:
  repository: 8kishore8/calculatorapp
  tag: latest
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000
  nodePort: 30011

imagePullSecrets:
  - name: dockerhub-secret

podLabels:
  app: app-calc

containerPort: 9090
