
replicaCount: 1

image:
  repository: web-calculator
  tag: latest
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  nodePort: 30010

imagePullSecrets:
  - name: dockerhub-secret

podLabels:
  app: web-calculator

containerPort: 80
