
replicaCount: 1

image:
  repository: 8kishore8/web-calculator
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000
  nodePort: 30010

imagePullSecrets:
  - name: dockerhub-secret

podLabels:
  app: web-calculator

containerPort: 3000

#ingress added
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: calculator.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - calculator.example.com
      secretName: calculator-tls
