
replicaCount: 1

image:
  repository: 8kishore8/web-calculator
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000
  nodePort: 30010

imagePullSecrets:
  - name: dockerhub-secret

podLabels:
  app: web-calculator

containerPort: 3000
